# This is the user configuration file, which is not specified. User can adopt yaml or any other formats according to their requirement.

approach_settings:
  video:
    tile_width_num: 1                         # number of horizontally segmented video tiles
    tile_height_num: 1                        # number of vertically segmented video tiles
    vam_size: [1680, 580]                      # resolution of the segmented frame
    crop_factor: [ '7 / 64', '7 / 48' ]      # Doubled denominators from [ '7 / 32', '7 / 24' ]
    scale_factors: { 1: '1', 1.5: '21 / 80', 2: '1 / 4', 3: '7 / 32', 4: '7 / 36', 5: '7 / 40', 6: '7 / 48', 7: '7 / 64' }  
  background:
    background_flag: False                    # whether to use background stream
  ffmpeg:
    ffmpeg_path: ~                            # absolute path, if there are different versions of ffmpeg, please specify the absolute path of the ffmpeg
    loglevel: error                           # log level of ffmpeg
    thread: 6                                 # number of threads running ffmpeg